### ISSUE TITLE
MaxHeap heapify malfunctions

### ISSUE THREAD

**Issue by heathcraig** [LukeBarcenas/FreQie#6]
MaxHeap does not output tokens in the correct order. Insert works fine, but extracting returns an incorrect order. I am almost certain that this is due to a problem with the heapify function, but I cannot identify any issues. All help is appreciated.

The py is attached, and the testing is done in the following manner:
from maxHeap import MaxHeap

words = ["nectarine", "tangerine", "cherry", "lemon", "papaya", "watermelon", "orange", "date", "tangerine", "apple", "honeydew", "yam", "orange", "quince", "raspberry", "strawberry", "cherry", "vanilla", "strawberry", "strawberry", "mango", "vanilla", "tangerine", "ugli", "grape", "tangerine", "strawberry", "banana", "banana", "cherry", "nectarine", "grape", "tangerine", "apple", "zucchini", "tangerine", "cherry", "watermelon", "raspberry", "date", "ugli", "raspberry", "grape", "grape", "raspberry", "zucchini", "strawberry", "yam", "vanilla", "zucchini", "mango", "quince", "elderberry", "strawberry", "strawberry", "tangerine", "banana", "honeydew", "tangerine", "watermelon", "lemon", "xigua", "honeydew", "lemon", "raspberry", "orange", "banana", "strawberry", "tangerine", "strawberry", "apple", "apple", "orange", "elderberry", "nectarine", "lemon", "fig", "yam", "honeydew", "yam", "yam", "elderberry", "orange", "vanilla", "raspberry", "fig", "orange", "papaya", "cherry", "orange", "nectarine", "vanilla", "strawberry", "watermelon", "fig", "kiwi", "fig", "apple", "tangerine", "kiwi", "banana", "cherry", "raspberry", "nectarine", "papaya", "elderberry", "strawberry", "ugli", "tangerine", "raspberry", "zucchini", "quince", "raspberry", "cherry", "banana", "vanilla", "strawberry", "strawberry", "kiwi", "honeydew", "honeydew", "strawberry", "orange", "date", "kiwi", "orange", "zucchini", "grape", "xigua", "vanilla", "tangerine", "orange", "honeydew", "papaya", "xigua", "elderberry", "raspberry", "zucchini", "grape", "zucchini", "quince", "cherry", "quince", "cherry", "nectarine", "kiwi", "strawberry", "strawberry", "yam", "grape", "watermelon", "elderberry", "fig", "watermelon", "strawberry", "apple", "nectarine", "orange", "lemon", "banana", "elderberry", "strawberry", "orange", "kiwi", "nectarine", "xigua", "lemon", "elderberry", "strawberry", "cherry", "zucchini", "lemon", "fig", "cherry", "zucchini", "orange", "elderberry", "yam", "xigua", "fig", "elderberry", "yam", "date", "xigua", "raspberry", "xigua", "watermelon", "xigua", "lemon", "orange", "orange", "fig", "quince", "orange", "apple", "cherry", "raspberry", "nectarine", "zucchini", "nectarine", "strawberry", "ugli", "xigua", "apple", "watermelon", "fig", "papaya", "elderberry", "elderberry", "watermelon", "ugli", "raspberry", "zucchini", "raspberry", "vanilla", "watermelon", "banana", "watermelon", "zucchini", "fig", "grape", "raspberry", "lemon", "zucchini", "papaya", "fig", "orange", "honeydew", "kiwi", "banana", "lemon", "xigua", "yam", "fig", "kiwi", "watermelon", "kiwi", "orange", "zucchini", "tangerine", "watermelon", "nectarine", "xigua", "watermelon", "raspberry", "strawberry", "nectarine", "fig", "mango", "raspberry", "mango", "zucchini", "date", "raspberry", "zucchini", "kiwi", "date", "date", "ugli", "grape", "quince", "ugli", "ugli", "cherry", "honeydew", "watermelon", "kiwi", "papaya", "cherry", "banana", "grape", "quince", "tangerine", "vanilla", "xigua", "raspberry", "banana", "date", "vanilla", "grape", "honeydew", "mango", "honeydew", "cherry", "elderberry", "fig", "quince", "cherry", "zucchini", "papaya", "watermelon", "orange", "cherry", "fig", "date", "watermelon", "quince", "honeydew", "raspberry", "banana", "lemon", "kiwi", "banana", "vanilla", "fig", "tangerine", "papaya", "honeydew", "mango", "watermelon", "quince", "raspberry", "watermelon", "tangerine", "grape", "honeydew", "yam", "date", "watermelon", "honeydew", "nectarine", "raspberry", "mango", "zucchini", "apple", "fig", "strawberry", "zucchini", "zucchini", "honeydew", "quince", "banana", "watermelon", "kiwi", "strawberry", "tangerine", "kiwi", "nectarine", "yam", "vanilla", "apple", "date", "orange", "zucchini", "watermelon", "zucchini", "orange", "xigua", "zucchini", "nectarine", "strawberry", "apple", "quince", "honeydew", "papaya", "raspberry", "fig", "strawberry", "zucchini", "ugli", "xigua", "honeydew", "xigua", "raspberry", "fig", "apple", "xigua", "tangerine", "fig", "vanilla", "honeydew", "raspberry", "honeydew", "watermelon", "lemon", "fig", "honeydew", "nectarine", "ugli", "raspberry", "tangerine", "ugli", "raspberry", "fig", "honeydew", "papaya", "ugli", "vanilla", "fig", "tangerine", "strawberry", "kiwi", "date", "date", "nectarine", "tangerine", "apple", "kiwi", "mango", "papaya", "orange", "zucchini", "vanilla", "elderberry", "zucchini", "strawberry", "quince", "nectarine", "xigua", "date", "apple", "mango", "kiwi", "vanilla", "cherry", "yam", "cherry", "quince", "zucchini", "grape", "date", "vanilla", "elderberry", "tangerine", "papaya", "date", "cherry", "banana", "date", "orange", "elderberry", "mango", "orange", "banana", "banana", "banana", "quince", "orange", "quince", "vanilla", "xigua", "orange", "tangerine", "vanilla", "tangerine", "fig", "honeydew", "vanilla", "papaya", "cherry", "apple", "papaya", "orange", "watermelon", "quince", "ugli", "banana", "watermelon", "raspberry", "strawberry", "fig", "vanilla", "orange", "lemon", "quince", "nectarine", "apple", "xigua", "papaya", "quince", "kiwi", "quince", "raspberry", "cherry", "fig", "watermelon", "raspberry", "yam", "mango", "lemon", "papaya", "vanilla", "grape", "apple", "orange", "orange", "zucchini", "grape", "quince", "zucchini", "tangerine", "papaya", "date", "tangerine", "mango", "mango", "grape", "orange", "nectarine", "kiwi", "kiwi", "elderberry", "grape", "quince", "apple", "lemon", "quince", "lemon", "ugli", "orange", "papaya", "tangerine", "date", "apple", "papaya", "honeydew", "ugli", "orange", "fig", "tangerine", "date", "cherry", "fig", "quince", "ugli", "xigua", "quince", "raspberry", "nectarine", "ugli", "grape", "cherry", "honeydew", "elderberry", "vanilla", "fig", "orange", "lemon", "yam", "strawberry", "xigua", "quince", "banana", "tangerine", "raspberry", "strawberry", "apple", "quince", "tangerine", "date", "grape", "kiwi", "quince", "raspberry", "honeydew", "elderberry", "ugli", "zucchini", "nectarine", "lemon", "orange", "mango", "cherry", "raspberry", "honeydew", "kiwi", "yam", "apple", "kiwi", "grape", "zucchini", "nectarine", "apple", "vanilla", "grape", "orange", "banana", "kiwi", "date", "orange", "papaya", "strawberry", "ugli", "lemon", "mango", "watermelon", "mango", "zucchini", "quince", "ugli", "kiwi", "date", "elderberry", "honeydew", "zucchini", "date", "raspberry", "fig", "raspberry", "honeydew", "date", "lemon", "honeydew", "fig", "strawberry", "xigua", "honeydew", "orange", "strawberry", "nectarine", "fig", "quince", "orange", "yam", "quince", "watermelon", "tangerine", "tangerine", "yam", "cherry", "apple", "apple", "lemon", "zucchini", "zucchini", "tangerine", "grape", "apple", "grape", "grape", "zucchini", "raspberry", "vanilla", "banana", "raspberry", "banana", "raspberry", "apple", "quince", "yam", "cherry", "strawberry", "papaya", "yam", "orange", "kiwi", "grape", "watermelon", "raspberry", "orange", "elderberry", "fig", "quince", "xigua", "strawberry", "watermelon", "zucchini", "tangerine", "mango", "cherry", "yam", "cherry", "date", "watermelon", "lemon", "elderberry", "kiwi", "mango", "kiwi", "grape", "cherry", "nectarine", "kiwi", "banana", "watermelon", "apple", "kiwi", "yam", "ugli", "honeydew", "papaya", "yam", "banana", "vanilla", "papaya", "zucchini", "ugli", "orange", "elderberry", "vanilla", "kiwi", "mango", "raspberry", "nectarine", "ugli", "watermelon", "cherry", "nectarine", "quince", "grape", "ugli", "yam", "yam", "xigua", "watermelon", "fig", "raspberry", "quince", "xigua", "quince", "orange", "xigua", "apple", "zucchini", "tangerine", "mango", "ugli", "xigua", "zucchini", "date", "mango", "honeydew", "ugli", "strawberry", "zucchini", "vanilla", "papaya", "fig", "fig", "raspberry", "strawberry", "tangerine", "grape", "cherry", "vanilla", "zucchini", "cherry", "mango", "raspberry", "yam", "cherry", "honeydew", "strawberry", "tangerine", "ugli", "banana", "apple", "apple", "tangerine", "xigua", "papaya", "lemon", "honeydew", "honeydew", "xigua", "lemon", "zucchini", "quince", "grape", "zucchini", "elderberry", "honeydew", "elderberry", "raspberry", "strawberry", "banana", "raspberry", "zucchini", "elderberry", "lemon", "cherry", "quince", "fig", "apple", "orange", "ugli", "cherry", "zucchini", "strawberry", "lemon", "quince", "apple", "mango", "zucchini", "raspberry", "zucchini", "banana", "xigua", "tangerine", "papaya", "zucchini", "apple", "cherry", "fig", "strawberry", "kiwi", "orange", "quince", "zucchini", "quince", "tangerine", "elderberry", "watermelon", "vanilla", "mango", "fig", "raspberry", "watermelon", "kiwi", "date", "lemon", "tangerine", "tangerine", "apple", "xigua", "tangerine", "fig", "strawberry", "yam", "banana", "date", "cherry", "vanilla", "lemon", "mango", "elderberry", "elderberry", "orange", "date", "nectarine", "vanilla", "banana", "banana", "apple", "vanilla", "ugli", "ugli", "ugli", "quince", "yam", "honeydew", "xigua", "papaya", "nectarine", "date", "zucchini", "watermelon", "strawberry", "kiwi", "cherry", "watermelon", "ugli", "kiwi", "elderberry", "mango", "xigua", "grape", "lemon", "honeydew", "papaya", "honeydew", "lemon", "cherry", "fig", "zucchini", "zucchini", "raspberry", "banana", "cherry", "elderberry", "cherry", "orange", "zucchini", "nectarine", "apple", "nectarine", "mango", "lemon", "yam", "vanilla", "nectarine", "orange", "yam", "date", "apple", "quince", "quince", "honeydew", "watermelon", "lemon", "xigua", "mango", "mango", "honeydew", "ugli", "date", "elderberry", "mango", "mango", "lemon", "papaya", "quince", "tangerine", "cherry", "ugli", "vanilla", "strawberry", "nectarine", "strawberry", "quince", "papaya", "cherry", "apple", "honeydew", "nectarine", "elderberry", "yam", "kiwi", "lemon", "zucchini", "honeydew", "elderberry", "yam", "lemon", "elderberry", "cherry", "xigua", "xigua", "vanilla", "apple", "cherry", "date", "raspberry", "banana", "mango", "banana", "mango", "nectarine", "honeydew", "zucchini", "grape", "apple", "nectarine", "zucchini", "vanilla", "banana", "orange", "vanilla", "ugli", "elderberry", "tangerine", "zucchini", "lemon", "vanilla", "raspberry", "kiwi", "orange", "fig", "vanilla", "orange", "fig", "ugli", "strawberry", "date", "apple", "honeydew", "lemon", "strawberry", "apple", "elderberry", "lemon", "fig", "papaya", "zucchini", "honeydew", "fig", "elderberry", "tangerine", "fig", "papaya", "watermelon", "elderberry", "vanilla", "tangerine", "mango", "orange", "xigua", "elderberry", "lemon", "apple", "mango", "ugli", "nectarine", "honeydew", "nectarine", "banana", "xigua", "yam", "strawberry", "honeydew", "orange", "lemon", "vanilla", "papaya", "strawberry", "kiwi", "quince", "honeydew", "elderberry", "ugli", "fig", "cherry", "papaya", "grape", "watermelon", "papaya", "watermelon", "ugli", "watermelon", "mango", "elderberry", "nectarine", "nectarine", "zucchini", "apple", "fig", "xigua", "ugli", "watermelon", "papaya", "watermelon", "xigua", "xigua", "date", "mango", "grape", "yam", "banana", "vanilla", "tangerine", "watermelon", "kiwi", "quince", "watermelon", "banana", "honeydew", "date", "watermelon", "banana", "vanilla", "watermelon", "ugli", "papaya", "zucchini", "cherry", "zucchini", "apple", "strawberry", "date", "orange", "banana", "tangerine", "nectarine", "elderberry", "lemon", "apple", "xigua", "nectarine", "vanilla", "banana", "kiwi", "quince", "grape", "fig", "banana", "honeydew", "mango", "banana", "vanilla", "apple", "nectarine", "tangerine", "kiwi", "fig", "orange", "mango", "orange", "raspberry", "cherry", "mango", "ugli", "fig", "watermelon", "banana", "zucchini", "zucchini", "raspberry", "mango", "tangerine", "mango", "watermelon", "quince", "yam", "honeydew", "fig", "strawberry", "quince", "fig", "banana", "honeydew", "date", "yam", "strawberry", "grape", "papaya", "cherry", "honeydew", "quince", "grape", "quince", "mango", "mango", "strawberry", "ugli", "date", "cherry", "raspberry", "ugli", "strawberry", "elderberry", "cherry", "banana", "strawberry", "grape", "ugli", "xigua", "quince", "zucchini", "mango", "papaya", "grape", "tangerine", "quince", "ugli", "watermelon", "elderberry", "fig", "yam", "zucchini", "xigua", "honeydew", "cherry", "ugli", "orange", "cherry", "papaya", "apple", "quince", "date", "strawberry", "grape", "date", "xigua", "elderberry", "orange", "banana", "mango", "nectarine", "nectarine", "tangerine", "papaya", "cherry", "quince", "date", "orange", "ugli", "mango", "raspberry", "zucchini", "fig", "mango", "honeydew", "strawberry", "honeydew", "xigua", "cherry", "elderberry", "yam", "grape", "raspberry", "apple", "strawberry", "elderberry", "nectarine", "zucchini", "strawberry", "papaya", "kiwi", "cherry", "yam", "fig", "lemon", "grape", "xigua", "ugli", "raspberry", "watermelon", "quince", "papaya", "grape", "yam", "cherry", "mango", "tangerine", "banana", "nectarine", "yam", "cherry", "watermelon", "mango", "fig", "xigua", "orange", "banana", "yam", "fig", "kiwi", "strawberry", "elderberry", "cherry", "raspberry", "fig", "grape", "apple", "tangerine", "strawberry", "kiwi", "banana", "fig", "papaya", "zucchini", "date", "strawberry", "papaya", "orange", "honeydew", "honeydew", "zucchini", "strawberry", "orange", "yam", "lemon", "lemon", "quince", "papaya", "apple", "kiwi", "watermelon", "watermelon", "watermelon", "orange", "lemon", "strawberry", "apple", "banana", "vanilla", "raspberry", "yam", "elderberry", "date", "elderberry", "fig", "kiwi", "honeydew", "raspberry", "ugli", "quince", "raspberry", "papaya", "yam", "tangerine", "yam", "watermelon", "apple", "quince", "date", "honeydew", "raspberry", "strawberry", "papaya", "ugli", "xigua", "elderberry", "date", "kiwi", "mango", "xigua", "xigua", "apple", "honeydew", "cherry", "tangerine", "nectarine", "banana", "nectarine", "kiwi", "tangerine", "zucchini", "tangerine", "strawberry", "nectarine", "yam", "watermelon", "honeydew", "tangerine", "vanilla", "vanilla", "banana", "vanilla", "nectarine", "quince", "strawberry", "tangerine", "vanilla", "nectarine", "strawberry", "banana", "grape", "yam", "banana", "elderberry", "strawberry", "apple", "cherry", "nectarine", "strawberry", "date", "strawberry", "papaya", "elderberry", "elderberry", "mango", "tangerine", "banana", "strawberry", "papaya", "grape", "elderberry", "banana", "grape", "apple", "quince", "quince", "ugli", "cherry", "cherry", "watermelon", "quince", "apple", "vanilla", "date", "orange", "fig", "zucchini", "banana", "mango", "raspberry", "nectarine", "grape", "ugli", "tangerine", "ugli", "elderberry", "xigua", "papaya", "kiwi", "raspberry", "elderberry", "watermelon", "date", "cherry", "ugli", "nectarine", "honeydew", "vanilla", "watermelon", "cherry", "ugli", "banana", "vanilla", "nectarine", "fig", "xigua", "papaya", "honeydew", "lemon", "orange", "mango", "fig", "ugli", "cherry", "date", "tangerine", "yam", "yam", "raspberry", "quince", "lemon", "cherry", "yam", "banana", "tangerine", "strawberry", "papaya", "honeydew", "grape", "raspberry", "grape", "grape", "strawberry", "grape", "apple", "lemon", "date", "strawberry", "xigua", "apple", "orange", "vanilla", "xigua", "date", "cherry", "elderberry", "watermelon", "watermelon", "apple", "tangerine", "orange", "fig", "nectarine", "apple", "date", "banana", "zucchini", "watermelon", "strawberry", "mango", "zucchini", "grape", "elderberry", "elderberry", "papaya", "lemon", "cherry", "date", "strawberry", "date", "orange", "date", "date", "orange", "grape", "watermelon", "kiwi", "yam", "raspberry", "mango", "vanilla", "raspberry", "apple", "banana", "mango", "xigua", "yam", "nectarine", "lemon", "raspberry", "zucchini", "honeydew", "fig", "cherry", "vanilla", "cherry", "lemon", "kiwi", "mango", "orange", "cherry", "watermelon", "elderberry", "ugli", "honeydew", "vanilla", "yam", "nectarine", "honeydew", "cherry", "zucchini", "raspberry", "xigua", "kiwi", "vanilla", "lemon", "vanilla", "vanilla", "watermelon", "kiwi", "papaya", "date", "watermelon", "zucchini", "elderberry", "watermelon", "vanilla", "fig", "grape", "ugli", "cherry", "nectarine", "fig", "yam", "papaya", "date", "zucchini", "grape", "xigua", "watermelon", "vanilla", "lemon", "banana", "zucchini", "kiwi", "papaya", "banana", "quince", "banana", "lemon", "apple", "papaya", "xigua", "yam", "banana", "elderberry", "papaya", "zucchini", "watermelon", "quince", "xigua", "lemon", "nectarine", "nectarine", "tangerine", "quince", "grape", "date", "orange", "date", "watermelon", "orange", "grape", "nectarine", "grape", "apple", "yam", "zucchini", "cherry", "elderberry", "vanilla", "raspberry", "cherry", "apple", "strawberry", "vanilla", "kiwi", "papaya", "zucchini", "nectarine", "strawberry", "tangerine", "tangerine", "xigua", "raspberry", "banana", "strawberry", "zucchini", "ugli", "grape", "apple", "raspberry", "grape", "date", "watermelon", "vanilla", "zucchini", "xigua", "banana", "watermelon", "orange", "papaya", "quince", "honeydew", "tangerine", "honeydew", "raspberry", "papaya", "xigua", "strawberry", "banana", "date", "apple", "yam", "raspberry", "kiwi", "vanilla", "zucchini", "apple", "quince", "kiwi", "yam", "yam", "lemon", "apple", "watermelon", "kiwi", "xigua", "cherry", "mango", "cherry", "tangerine", "lemon", "zucchini", "zucchini", "vanilla", "raspberry", "strawberry", "grape", "vanilla", "fig", "mango", "kiwi", "ugli", "strawberry", "quince", "apple", "zucchini", "ugli", "zucchini", "quince", "yam", "fig", "date", "yam", "yam", "fig", "quince", "elderberry", "tangerine", "zucchini", "kiwi", "date", "papaya", "orange", "vanilla", "watermelon", "raspberry", "zucchini", "kiwi", "strawberry", "watermelon", "strawberry", "mango", "strawberry", "elderberry", "date", "lemon", "quince", "watermelon", "ugli", "vanilla", "strawberry", "fig", "honeydew", "watermelon", "apple", "ugli", "nectarine", "apple", "ugli", "zucchini", "date", "apple", "strawberry", "papaya", "watermelon", "elderberry", "banana", "zucchini", "cherry", "banana", "papaya", "tangerine", "cherry", "tangerine", "xigua", "cherry", "fig", "honeydew", "fig", "apple", "honeydew", "orange", "tangerine", "quince", "kiwi", "kiwi", "zucchini", "lemon", "apple", "banana", "watermelon", "kiwi", "nectarine", "orange", "date", "tangerine", "banana", "nectarine", "papaya", "grape", "grape", "quince", "cherry", "xigua", "zucchini", "apple", "xigua", "papaya", "fig", "yam", "kiwi", "elderberry", "orange", "fig", "tangerine", "xigua", "nectarine", "apple", "apple", "date", "vanilla", "banana", "vanilla", "lemon", "quince", "vanilla", "honeydew", "nectarine", "kiwi", "xigua", "mango", "zucchini", "raspberry", "zucchini", "date", "honeydew", "tangerine", "papaya", "strawberry", "ugli", "tangerine", "lemon", "xigua", "fig", "watermelon", "mango", "strawberry", "date", "grape", "elderberry", "strawberry", "honeydew", "vanilla", "yam", "papaya", "lemon", "cherry", "kiwi", "kiwi", "orange", "cherry", "mango", "raspberry", "fig", "nectarine", "vanilla", "banana", "mango", "orange", "vanilla", "date", "grape", "raspberry", "mango", "grape", "elderberry", "yam", "date", "grape", "strawberry", "banana", "nectarine", "papaya", "apple", "kiwi", "quince", "zucchini", "apple", "ugli", "date", "elderberry", "ugli", "cherry", "papaya", "fig", "zucchini", "zucchini", "raspberry", "elderberry", "yam", "nectarine", "papaya", "kiwi", "elderberry", "orange", "raspberry", "strawberry", "raspberry", "apple", "vanilla", "banana", "nectarine", "cherry", "lemon", "grape", "mango", "quince", "yam", "honeydew", "raspberry", "quince", "fig", "ugli", "date", "lemon", "zucchini", "vanilla", "vanilla", "date", "raspberry", "nectarine", "elderberry", "kiwi", "papaya", "watermelon", "tangerine", "raspberry", "kiwi", "elderberry", "kiwi", "papaya", "tangerine", "yam", "cherry", "yam", "strawberry", "fig", "strawberry", "fig", "apple", "ugli", "kiwi", "mango", "lemon", "orange", "elderberry", "watermelon", "fig", "nectarine", "nectarine", "orange", "kiwi", "elderberry", "ugli", "kiwi", "quince", "honeydew", "apple", "watermelon", "lemon", "xigua", "honeydew", "vanilla", "grape", "quince", "yam", "date", "cherry", "fig", "xigua", "nectarine", "watermelon", "fig", "zucchini", "honeydew", "elderberry", "grape", "elderberry", "yam", "zucchini", "vanilla", "date", "apple", "yam", "watermelon", "banana", "banana", "vanilla", "apple", "honeydew", "quince", "quince", "tangerine", "xigua", "quince", "date", "zucchini", "orange", "kiwi", "strawberry", "kiwi", "yam", "orange", "elderberry", "orange", "orange", "strawberry", "mango", "papaya", "orange", "nectarine", "elderberry", "date", "lemon", "grape", "tangerine", "strawberry", "apple", "xigua", "watermelon", "honeydew", "xigua", "kiwi", "elderberry", "elderberry", "orange", "watermelon", "elderberry", "zucchini", "apple", "orange", "orange", "papaya", "honeydew", "date", "xigua", "papaya", "raspberry", "papaya", "honeydew", "papaya", "grape", "vanilla", "nectarine", "elderberry", "fig", "xigua", "papaya", "elderberry", "cherry", "nectarine", "orange", "zucchini", "vanilla", "banana", "tangerine", "papaya", "yam", "cherry", "zucchini", "fig", "kiwi", "xigua", "fig", "watermelon", "raspberry", "nectarine", "mango", "xigua", "fig", "lemon", "xigua", "xigua", "quince", "apple", "nectarine", "honeydew", "orange", "papaya", "nectarine", "orange", "grape", "orange", "raspberry", "strawberry", "fig", "apple", "tangerine", "elderberry", "nectarine", "mango", "date", "quince", "banana", "watermelon", "apple", "strawberry", "ugli", "vanilla", "yam", "watermelon", "ugli", "elderberry", "ugli", "tangerine", "cherry", "kiwi", "yam", "lemon", "honeydew", "elderberry", "xigua", "banana", "tangerine", "honeydew", "quince", "date", "lemon", "ugli", "tangerine", "date", "quince", "raspberry", "cherry", "cherry", "orange", "papaya", "raspberry", "elderberry", "yam", "mango", "elderberry", "zucchini", "banana", "tangerine", "grape", "lemon", "apple", "ugli", "grape", "quince", "zucchini", "banana", "lemon", "strawberry", "xigua", "quince", "cherry", "watermelon", "vanilla", "tangerine", "quince", "xigua", "honeydew", "banana", "apple", "raspberry", "watermelon", "honeydew", "banana", "yam", "vanilla", "apple", "watermelon", "cherry", "yam", "quince", "grape", "apple", "grape", "nectarine", "papaya", "honeydew", "quince", "quince", "zucchini", "grape", "nectarine", "watermelon", "lemon", "orange", "yam", "yam", "zucchini", "fig", "ugli", "grape", "strawberry", "elderberry", "watermelon", "honeydew", "cherry", "xigua", "quince", "watermelon", "honeydew", "watermelon", "ugli", "date", "date", "grape", "banana", "tangerine", "grape", "yam", "xigua", "honeydew", "mango", "raspberry", "grape", "quince", "tangerine", "raspberry", "yam", "fig", "zucchini", "ugli", "cherry", "watermelon", "orange", "fig", "elderberry", "nectarine", "date", "apple", "fig", "mango", "lemon", "tangerine", "apple", "cherry", "xigua", "strawberry", "cherry", "grape", "zucchini", "cherry", "raspberry", "papaya", "vanilla", "mango", "quince", "quince", "quince", "vanilla", "kiwi", "date", "papaya", "papaya", "orange", "mango", "strawberry", "yam", "elderberry", "date", "zucchini", "fig", "papaya", "zucchini", "apple", "lemon", "date", "cherry", "nectarine", "banana", "watermelon", "kiwi", "watermelon", "date", "ugli", "orange", "cherry", "raspberry", "cherry", "tangerine", "honeydew", "kiwi", "lemon", "date", "cherry", "elderberry", "yam", "yam", "nectarine", "fig", "date", "grape", "papaya", "date", "mango", "quince", "banana", "tangerine", "raspberry", "zucchini", "strawberry", "quince", "ugli", "elderberry", "elderberry", "zucchini", "xigua", "fig", "lemon", "vanilla", "nectarine", "xigua", "apple", "nectarine", "elderberry", "raspberry", "lemon", "watermelon", "zucchini", "kiwi", "watermelon", "date", "honeydew", "honeydew", "grape", "yam", "yam", "cherry", "ugli", "honeydew", "grape", "papaya", "orange", "quince", "vanilla", "elderberry", "vanilla", "quince", "vanilla", "grape", "cherry", "date", "apple", "elderberry", "mango", "banana", "elderberry", "orange", "fig", "papaya", "quince", "orange", "lemon", "papaya", "ugli", "zucchini", "honeydew", "watermelon", "yam", "grape", "apple", "mango", "quince", "raspberry", "yam", "kiwi", "xigua", "zucchini", "nectarine", "quince", "cherry", "banana", "papaya", "ugli", "nectarine", "banana", "raspberry", "yam", "fig", "vanilla", "banana", "elderberry", "cherry", "yam", "nectarine", "honeydew", "strawberry", "papaya", "quince", "zucchini", "banana", "quince", "papaya", "date", "xigua", "yam", "zucchini", "kiwi", "zucchini", "watermelon", "honeydew", "fig", "watermelon", "apple", "date", "quince", "fig", "date", "raspberry", "watermelon", "orange", "yam", "zucchini", "kiwi", "yam", "quince", "vanilla", "apple", "mango", "fig", "kiwi", "nectarine", "ugli", "quince", "honeydew", "cherry", "lemon", "vanilla", "tangerine", "ugli", "yam", "xigua", "elderberry", "vanilla", "xigua", "fig", "watermelon", "kiwi", "papaya", "raspberry", "elderberry", "quince", "papaya", "date", "papaya", "strawberry", "tangerine", "apple", "lemon", "tangerine", "apple", "elderberry", "lemon", "raspberry", "kiwi", "raspberry", "ugli", "xigua", "yam", "honeydew", "nectarine", "zucchini", "orange", "lemon", "elderberry", "watermelon"]
# Adds tokens to maxheap

maxHeap = MaxHeap(words)
maxHeap.print_top_n(X)
[maxHeappy.txt](https://github.com/user-attachments/files/17966610/maxHeappy.txt)

**Comment by LukeBarcenas** [comment]
Fixed in commit: e11f103461d27e38262a697e8f1976a60b1de7aa ("Added maxHeap.py to resolve issue #2
Fixed heapify implementation to resolve issue #6")
